apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    description: "Nginx deployment managed by ops agent"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:1.23.3
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
        securityContext:
          readOnlyRootFilesystem: false